runner: Fix globbing and report skipped scripts

diff --git a/bin/runner b/bin/runner
--- a/bin/runner
+++ b/bin/runner
@@ -16,21 +16,26 @@ case "$op" in
    setup|extract|essential|customize|cleanup)
       for dir in "${dirs[@]}" ; do
          [[ -d "$dir" ]] || continue
-         scripts=("${dir}/${op}"*)
-         for script in "${scripts[@]}" ; do
-            if [ -x "$script" ] ; then
+         if compgen -G "${dir}/${op}*" >/dev/null; then
+            for script in "${dir}/${op}"* ; do
                s=$(basename "$script")
-               if [[ $s =~ ^[a-zA-Z0-9-]+$ ]] ; then
-                  echo "runner: $dir [$s]"
-                  env -C "$dir" bash "$s" "$@"
-                  err=$?
-                  if [ $err -ne 0 ] ; then
-                     >&2 echo "runner: $script error ($err)"
-                     exit $err
+               if [ -x "$script" ] ; then
+                  if [[ $s =~ ^[a-zA-Z0-9-]+$ ]] ; then
+                     echo "runner: $dir [run $s]"
+                     env -C "$dir" bash "$s" "$@"
+                     err=$?
+                     if [ $err -ne 0 ] ; then
+                        >&2 echo "runner: $script error ($err)"
+                        exit $err
+                     fi
+                  else
+                     >&2 echo "runner: $dir [skipped $s]"
                   fi
+               else
+                  >&2 echo "runner: $dir [ignored $s]"
                fi
-            fi
-         done
+            done
+         fi
       done
       ;;
    *)
